name: Simple Action
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send a Slack Message
        uses: ./.github/actions/slack-php
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          message: Hello Slack - New deployment
      - name: Send a Slack Message
        uses: ./.github/actions/slack-joke
        with:
          slack_username: jlimabr
          upload_joke: true
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
      - name: Displaying joke output
        run: echo '${{ steps.slack-joke.outputs.joke }}'
      - name: Simple JS Action
        id: greet
        uses: ./.github/actions/hello
        with:
          who_to_greet: Ali

